"""PyTorch-native analytical and classical mechanics."""

from ._native import NativeExtensionUnavailable, native_spring_available, native_spring_status
from .analytical import HamiltonianSystem, LagrangianSystem, canonical_transformation_residual
from .classical import (
    angular_momentum,
    center_of_mass,
    hooke_spring_force,
    kinetic_energy,
    linear_momentum,
    near_surface_gravity_force,
    newton_residual,
)
from .control import (
    LQRResult,
    feedback_rollout,
    finite_horizon_lqr,
    infinite_horizon_lqr,
    quadratic_cost,
    rollout_cost,
    tvlqr,
)
from .diagnostics import DiagnosticsReport, energy_drift, lagrangian_diagnostics, residual_stats
from .dynamics import (
    euler_state_step,
    discrete_step,
    discretize_linearization,
    hamiltonian_dynamics,
    join_state,
    linearize,
    linearize_discrete,
    rk4_state_step,
    rollout,
    second_order_dynamics,
    split_state,
)
from .fit import FitResult, fit_hamiltonian_residual, fit_lagrangian_residual, fit_rollout
from .integrators import euler_step, rk4_step, semi_implicit_euler_step, velocity_verlet_step
from .kinematics import estimate_acceleration, estimate_velocity
from .learning import (
    HamiltonianModule,
    LagrangianModule,
    hamiltonian_residual_loss,
    lagrangian_residual_loss,
    residual_loss,
)
from .robotics import (
    ManipulatorTerms,
    bias_forces,
    computed_torque,
    forward_dynamics,
    gravity_forces,
    inverse_dynamics,
    lagrangian_state_dynamics,
    manipulator_terms,
    mass_matrix,
    velocity_forces,
)

__all__ = [
    "DiagnosticsReport",
    "FitResult",
    "HamiltonianModule",
    "HamiltonianSystem",
    "LQRResult",
    "LagrangianModule",
    "LagrangianSystem",
    "ManipulatorTerms",
    "NativeExtensionUnavailable",
    "angular_momentum",
    "bias_forces",
    "canonical_transformation_residual",
    "center_of_mass",
    "computed_torque",
    "discrete_step",
    "discretize_linearization",
    "energy_drift",
    "estimate_acceleration",
    "estimate_velocity",
    "euler_step",
    "euler_state_step",
    "feedback_rollout",
    "finite_horizon_lqr",
    "fit_hamiltonian_residual",
    "fit_lagrangian_residual",
    "fit_rollout",
    "forward_dynamics",
    "gravity_forces",
    "hamiltonian_dynamics",
    "hamiltonian_residual_loss",
    "hooke_spring_force",
    "inverse_dynamics",
    "infinite_horizon_lqr",
    "join_state",
    "kinetic_energy",
    "lagrangian_diagnostics",
    "lagrangian_residual_loss",
    "lagrangian_state_dynamics",
    "linear_momentum",
    "linearize",
    "linearize_discrete",
    "manipulator_terms",
    "mass_matrix",
    "near_surface_gravity_force",
    "native_spring_available",
    "native_spring_status",
    "newton_residual",
    "quadratic_cost",
    "residual_loss",
    "residual_stats",
    "rk4_step",
    "rk4_state_step",
    "rollout",
    "rollout_cost",
    "semi_implicit_euler_step",
    "second_order_dynamics",
    "split_state",
    "tvlqr",
    "velocity_forces",
    "velocity_verlet_step",
]

__version__ = "0.1.0"
